//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PackageObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class AHero : ABaseGameObject
	{		

		public virtual Characteristic attack
		{
			get;
			set;
		}

		public virtual Characteristic defence
		{
			get;
			set;
		}

		public virtual Characteristic health
		{
			get;
			set;
		}

		public virtual Characteristic life
		{
			get;
			set;
		}

		public override string description
		{
			get;
			set;
		}

		public override int id
		{
			get;
			set;
		}

		public override float mass
		{
			get;
			set;
		}

		public override string name
		{
			get;
			set;
		}

		public virtual void Damage()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Injunre()
		{
			throw new System.NotImplementedException();
		}

		public abstract void Move();

		public virtual void Save()
		{
			throw new System.NotImplementedException();
		}

	}
}

